### ISSUE TITLE
Set up a basic bot

### ISSUE THREAD

**Issue by rishabhKalakoti** [Codeshows/telegram-bot#1]
(Python): Bot tutorial- freecodecamp
https://medium.freecodecamp.org/learn-to-build-your-first-bot-in-telegram-with-python-4c99526765e4
(Python) Django tutorial for making a bot:
https://khashtamov.com/en/how-to-create-a-telegram-bot-using-python/
https://khashtamov.com/en/how-to-deploy-telegram-bot-django/
NodeJS telegram bot:
https://blog.srnd.org/intro-to-node-js-making-a-telegram-bot-964b8cfe1129

Googling is the best so feel free to google. You can add in comments if you find better resources.

**Comment by Pankajtanwarbanna** [comment]
Should go for NodeJs. real-time, push-based architecture and non-blocking, event-driven server would be a plus point for bot application.

**Comment by rishabhKalakoti** [comment]
I am fine with any. Does't make much of a difference which language we choose, all would be sufficient for the bot we plan to design
